- name: install epel repo, grid and pool account setting
  hosts: all
  tasks:
    - yum:
        name: epel-release
        state: present
    - replace:
        path: /etc/yum.repos.d/epel.repo
        regexp: '^#baseurl'
        replace: 'baseurl'
    - replace:
        path: /etc/yum.repos.d/epel.repo
        regexp: '^metalink'
        replace: '#metalink'
   
   

