---
- name: dCache for dcache non-pool server
  hosts: head
  vars: 
    - dcache_version: 7.2.15
  become: true
  no_log: false
  roles:
    - role: geonmo.dcache
      vars:
        type: "frontend"
      
- name: dCache for dcache pool server
  hosts: disk
  vars: 
    - dcache_version: 7.2.15
    - volume_path: /mnt/dcache
    - headnode: belle-se2-head.sdfarm.kr
  become: true
  roles:
    - role: geonmo.dcache
      vars:
        type: "backend"
