---
- name: dCache for Client
  become: true
  hosts: client
  roles:
    - role: geonmo.dcache
      vars:
        type: "client"

- name: dCache for dcache non-pool server
  hosts: frontend
  become: true
  no_log: false
  roles:
    - role: geonmo.dcache
      vars:
        type: "frontend"
      
- name: dCache for dcache pool server
  hosts: backend
  become: true
  roles:
    - role: geonmo.dcache
      vars:
        type: "backend"
