- name: nfs setup
  become: true
  hosts: backend
  tasks:
    - yum:
        name: nfs-utils
        state: present
    - lineinfile: 
        path: /etc/exports
        line: "/mnt/ramdisk     *(rw,fsid=1,no_subtree_check)"
    - service:
        name: "{{ item }}"
        state: started
      with_items: 
        - nfs-server
        - nfs-idmapd
        - nfs-mountd

- name: nfs mount
  become: true
  hosts: client
  tasks:
    - mount:
        path: /mnt/ramdisk_node2
        src:  node2.intranet.local:/mnt/ramdisk
        fstype: nfs
        opts: defaults,noauto
        state: present
    - mount:
        path: /mnt/ramdisk_node3
        src:  node3.intranet.local:/mnt/ramdisk
        fstype: nfs
        opts: defaults,noauto
        state: present


          
