---
- name: provisioning
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  become: true
  vars:
    users:
    - { userid: 'geonmo', sshpubkey: 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAx3hsrp0tvlSt/Icp2hGQxeRmlIejJTugj/v4DnoztKRQIIiRgWKHDpxKji1eR7A9YusN51G6bZL5RZzJSfgbWiVBfmAKNfiQjHMte80vQlWdtTVXXff05k+aslqUWUTnuquhRnbS0hngamFrISW5/cQMDWUXEi0E4+UKcweG4pWsAYOaFgshj9dQ63JtOMOmbamhXNMxwhtFViQMSHVrEikHXsVIQx6bt64CYjQoGkkyXyqb5AdOtUtwDgRp/GIJSTia78NugdlGY/SdGmYlFR00LpNOqVoJ1tDRS6TniCmx26gTiUUYVDZ84WyNtvwFDaSphdBDDn3rXlgEuf9iBQ== geonmo@ui10.sdfarm.kr'}
    - { userid: 'kong91', sshpubkey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRLsG4JEHo3FKKirYL7VoOjASQNDxyCDbDsQ+zoI2L6o3zrvyoh7mEjQEybWNgRpJnkuWMS2Kg14079thb5wRqfMlYrhoird4YK3eVOxfzDDd7YaJiTA3WlHwoZCkOP7XeqM51nmS/I6a8hksVsBe3ewUtglpfGcD0lTe7Ug+1pLvJdTZLjl50V3dj730Ilx9MdPFUypD2Rtlwnovont4SXJPVVfjcoEEsr98A9e7w2mTjUt6s6aGdxQgnKYXwzNMCv+1I+/eaeoU4qrYEL9xDF14M/2CGLGr7A40G7WtfE1Dqvos7WhXpjDVEEUnUzKVj5m6fXAJb9nlSt2yLT4jX kong91@K0843P1ui-iMac.local'}
  tasks:
    - user:
        name: "{{ item.userid }}"
      with_items:
      - "{{ users }}"
    - file:
        path: "~{{ item.userid }}/.ssh"
        owner: "{{ item.userid }}"
        group: "{{ item.userid }}"
        mode: "0755"
        state: directory
      with_items:
      - "{{ users }}"
    - copy:
        dest: "~{{ item.userid }}/.ssh/authorized_keys"
        content: "{{ item.sshpubkey }}"
        owner: "{{ item.userid }}"
        group: "{{ item.userid }}"
        mode: "0700"
      with_items:
      - "{{ users }}"
    - lineinfile:
        path: "/etc/hosts"
        line: "192.168.10.3 node0.intranet.local    node0\n192.168.10.4  node1.intranet.local    node1\n192.168.10.5  node2.intranet.local    node2\n192.168.10.6  node3.intranet.local    node3\n"
    - copy:
        dest: "/etc/sudoers.d/geonmo"
        content: "geonmo    ALL=(ALL)   NOPASSWD: ALL"

      
