---
- name: XRootD for Client
  become: true
  hosts: client
  roles:
    - role: geonmo.xrootd 
      vars:
        type: "client"

- name: XRootD for rdr
  hosts: frontend
  become: true
  roles:
    -  role: geonmo.xrootd
       vars:
         type: "frontend"
         rdr: "node1.intranet.local"
         device: "enp0s8"
      
- name: XRootD for server
  hosts: backend
  become: true
  roles:
    - role: geonmo.xrootd
      vars:
        type: "backend"
        dir: "/mnt/ramdisk"
        rdr: "node1.intranet.local"
        device: "enp0s8"
