# -*- mode: ruby -*-
# vi: set ft=ruby :

NODE_COUNT = 4
VAGRANT_EXPERIMENTAL="disks"

Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = false
     # Customize the amount of memory on the VM:
     vb.memory = "10240"
     vb.linked_clone = true     
     #(0..3).each do |i|
     #  vb.disk :disk, name: "storage-#{i}", size: "30GB"
     #end
   end

  NODE_COUNT.times do |i|
    node_id = "node#{i}"
    ip_addressPublic = "192.168.10.#{i+3}"
    ip_address10 = "192.168.10.#{i+3}"
    ip_address20 = "192.168.20.#{i+3}"
    config.vm.define node_id do |node|
      node.vm.box = "geerlingguy/centos7"
      node.vm.box_download_insecure=true
      node.vm.hostname = "#{node_id}.intranet.local"      
      node.vm.synced_folder ".vagrant", "/home/vagrant/.vagrant"
      
      node.vm.network "private_network", ip: "#{ip_address10}", hostname: false, virtualbox__intnet: "Skynet"
      node.vm.network "private_network", ip: "#{ip_address20}", hostname: false, virtualbox__intnet: "condor_net", nic_type: "virtio"
      node.vm.network "forwarded_port", guest: 22, host: "#{i+2222}"
      node.vm.provision "shell", inline: <<-SHELL
        cp /home/vagrant/.vagrant/machines/#{node_id}/virtualbox/private_key /home/vagrant/.ssh/id_rsa
        cp /home/vagrant/.ssh/authorized_keys /home/vagrant/.ssh/id_rsa.pub
        cat /home/vagrant/.ssh/authorized_keys >> /home/vagrant/.vagrant/authorized_keys
        cat /home/vagrant/.vagrant/authorized_keys >> /home/vagrant/.ssh/authorized_keys                    
        chown vagrant.vagrant /home/vagrant/.ssh/id_rsa*
        chmod 644 /home/vagrant/.ssh/id_rsa.pub
        chmod 400 /home/vagrant/.ssh/id_rsa        
        mkdir /mnt/ramdisk
        echo "tmpfs /mnt/ramdisk tmpfs defaults,size=4G 0 0"  >> /etc/fstab

        
        openssl s_client -showcerts -servername "github.com/" -connect github.com:443 >  /etc/pki/ca-trust/source/anchors/somansa.crt        
        update-ca-trust force-enable
        update-ca-trust extract

        yum install -y git vim centos-release-ansible-29.noarch
        yum install -y ansible
        cd $HOME
        git clone https://github.com/geonmo/desktop_vagrant.git        
        cd desktop_vagrant
        ansible-playbook provision.yml        

      SHELL
    end
  end  
end
