# -*- mode: ruby -*-
# vi: set ft=ruby :

NODE_COUNT = 4
VAGRANT_EXPERIMENTAL="disks"

Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = false
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
     vb.linked_clone = true     
     #(0..3).each do |i|
     #  vb.disk :disk, name: "storage-#{i}", size: "30GB"
     #end
   end

  NODE_COUNT.times do |i|
    node_id = "node#{i}"
    ip_address = "192.168.10.#{i+3}"
    config.vm.define node_id do |node|
      node.vm.box = "geerlingguy/centos7"
      node.vm.box_download_insecure=true
      node.vm.hostname = "#{node_id}.intranet.local"
      node.vm.disk :disk, name: "storage-#{node_id}", size: "30GB" 
      
      node.vm.network "private_network", ip: "#{ip_address}", 
        virtualbox__intnet: "condor_net"
      node.vm.network "forwarded_port", guest: 22, host: "#{i+2222}"
      node.vm.provision "shell", inline: <<-SHELL
        
        openssl s_client -showcerts -servername "github.com/" -connect github.com:443 >  /etc/pki/ca-trust/source/anchors/somansa.crt        
        update-ca-trust force-enable
        update-ca-trust extract

        yum install -y git vim centos-release-ansible-29.noarch
        yum install -y ansible
        rm -rf /tmp/ansible_provision
        git clone https://github.com/geonmo/desktop_vagrant.git /tmp/ansible_provision
        cd /tmp/ansible_provision
        ansible-playbook provision.yml        
      SHELL
    end
  end  
end
